title: AutoReply
modelClass: Beysong\Weixin\Models\Autoreply
list: $/beysong/weixin/models/autoreply/columns.yaml
recordUrl: 'beysong/weixin/autoreply/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
